### ISSUE TITLE
Wrong Interfaces

### ISSUE THREAD

**Issue by sakiss** [ashsmith/magento2-blog-module-tutorial#5]
files: 
Blog/Model/Post.php
Blog/Block/PostList.php

\Magento\Framework\DataObject\IdentityInterface _does not exist_
replace it with:
\Magento\Framework\Object\IdentityInterface

**Comment by ashsmith** [comment]
This is fixed in the latest version of the module: https://github.com/ashsmith/magento2-blog-module-tutorial/commit/368106f415169239803e601b52351085940dffcb

This issue does exist on previous releases though. I intend on fixing the previous versions soon though :+1:

**Comment by sakiss** [comment]
I installed the extension through composer following the command you have here in github.
So i suppose that the problem exists in the package you distribute

**Comment by ashsmith** [comment]
The current version is 0.5.2-stable, which includes the commit I referenced. https://github.com/ashsmith/magento2-blog-module-tutorial/tree/0.5.2-stable

I can only imagine you have installed a later version.

**Comment by ashsmith** [comment]
@sakiss Can you try the latest version: `0.5.4-stable` I have reverted my change that broke this for you.

I've been using the latest version of Magento 2, cloned directly from the git repo, and there has been ongoing changes which has broken my module multiple times, hence why I've had to implement that fix. I'm guessing you have installed Magento 2 via composer, which is currently behind the M2 github repo (because you'll be on the Merchant Beta, which was released in June/July)

As a reference for other people looking at this, `dev-develop` or `dev-master` are being kept up to date with the Magento 2 repository as it changes, the branches and 0.x releases are based on installing Magento 2 via composer.
